apiVersion: v1
kind: Pod
metadata:
  name: custom-scheduler499
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: custom-scheduler-container
    image: giulia99/task_carousel:first_tag
    command: ["python","task_driver.py"]
    args: ["3", "1"]
  restartPolicy: OnFailure
  
